CREATE TABLE `author` (
  `AUTHOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUTHOR_NAME` varchar(100) NOT NULL,
  `AUTHOR_SEX` char(1) NOT NULL,
  `AUTHOR_DOB` varchar(20) NOT NULL,
  `DESC` nvarchar(200) NOT NULL,
  `REG_DATE` date DEFAULT NULL,
  `REG_USER_ID` char(20) DEFAULT NULL,
  `UPD_DATE` date DEFAULT NULL,
  `UPD_USER_ID` char(20) DEFAULT NULL,
  `DEL_DATE` date DEFAULT NULL,
  `DEL_USER_ID` char(20) DEFAULT NULL,
  `DEL_FLG` char(1) NOT NULL,
  PRIMARY KEY (`AUTHOR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE `book_info` (
  `BOOK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOOK_NAME` varchar(100) NOT NULL,
  `BOOK_ISBN` varchar(20) NOT NULL,
  `REG_DATE` date DEFAULT NULL,author
  `REG_USER_ID` char(20) DEFAULT NULL,
  `UPD_DATE` date DEFAULT NULL,
  `UPD_USER_ID` char(20) DEFAULT NULL,
  `DEL_DATE` date DEFAULT NULL,
  `DEL_USER_ID` char(20) DEFAULT NULL,
  `DEL_FLG` char(1) NOT NULL,
  PRIMARY KEY (`BOOK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
